name: Documentation

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: 1.10  # 或者指定你需要的 Julia 版本

    - name: Install dependencies
      run: julia --project=docs -e 'using Pkg; Pkg.instantiate()'

    - name: Build and deploy documentation
      env:
        GITHUB_TOKEN: ${{ secrets.DOCUMENTER_KEY }}
      run: julia --project=docs docs/make.jl
